const team = [
  {
    slug: "murtaza-humayun",
    name: "Murtaza humayun",
    role: "Lead Developer",
    bio: "Ships fast, breaks nothing. The person who says 'we can build that'.",
    photo: "/team1.webp",
    gradient: 180,
    years: "2 yrs",
    based: "Lahore, PK",
    quote: "Turning ideas into fast, beautiful, and meaningful digital experiences.",
    orbit: ["Engineering", "Web", "Development", "Performance", "Systems", "Delivery"],
    skills: [
      { label: "Frontend Engineering", level: 97 },
      { label: "WebGL / Three.js", level: 88 },
      { label: "Backend / APIs", level: 78 },
      { label: "DevOps", level: 74 },
    ],
    toolkit: ["TypeScript", "React", "Three.js", "GSAP", "TailwindCSS"],
    projects: [
      { name: "Kōra Studio Site", year: "2025", tag: "Web" },
      { name: "Volt Configurator", year: "2024", tag: "3D" },
      { name: "Nomi Web App", year: "2024", tag: "Product" },
    ],
    contact: { email: "dev@hiiipe.com", handle: "@murtazahumayun" },
  },
  {
    slug: "abdullah-zeeshan",
    name: "Abdullah Zeeshan",
    role: "founder",
    bio: "Makes pixels move like they mean it. Cinema 4D and After Hours.",
    photo: "/team3.webp",
    gradient: 240,
    years: "2 yrs",
    based: "London, UK",
    quote: "If it doesn't move, it doesn't matter.",
    orbit: ["Motion", "3D", "Direction", "Render", "Rhythm", "Frames"],
    skills: [
      { label: "Motion Design", level: 96 },
      { label: "3D / Cinema 4D", level: 93 },
      { label: "Direction", level: 87 },
      { label: "Sound Design", level: 74 },
    ],
    toolkit: ["Cinema 4D", "Octane", "After Effects", "Blender", "Houdini"],
    projects: [
      { name: "Volt Launch Film", year: "2025", tag: "Motion" },
      { name: "Field Notes Reel", year: "2024", tag: "3D" },
      { name: "Ora Product Loop", year: "2023", tag: "Loop" },
    ],
    contact: { email: "core@hiiipe.com", handle: "@abdullahzee" },
  },
  {
    slug: "muhammad-asad",
    name: "Muhammad Asad",
    role: "Marketing Head",
    bio: "Helping businesses grow through strategic content, SEO, AI-powered marketing, and data-driven storytelling.",
    photo: "/team2.webp",
    gradient: 300,
    years: "3 yrs",
    based: "Lahore, Pk",
    quote: "Short sentences. Long memories.",
    orbit: ["Content", "SEO", "SocialMedia", "AI Marketing", "Meta Ads", "Story"],
    skills: [
      { label: "SEO", level: 96 },
      { label: "Copywriting", level: 97 },
      { label: "Meta Ads", level: 88 },
      { label: "Google Analytics", level: 86 },
    ],
    toolkit: ["Claude", "Google Analytics", "Grammarly", "Canva", "Gemini", "Notion", "Ahrefs", "Semrush"],
    projects: [
      { name: "Kōra Voice Guide", year: "2025", tag: "Voice" },
      { name: "Volt Tagline System", year: "2024", tag: "Naming" },
      { name: "Field Notes Vol. II", year: "2023", tag: "Editorial" },
    ],
    contact: { email: "ops@hiiipe.com", handle: "@asadwarrior" },
  },
];
export default team;

// export const getMember = (slug) => team.find((m) => m.slug === slug);
